### PR TITLE
Expanded support for Euler angles conversions: the order of rotations can now be specified everywhere

### PR DESCRIPTION
**Pull request by ThomasGorisse**

### CODE REVIEW

**Review by romainguy — APPROVED** [review]

**Comment by ThomasGorisse** [comment]
Wait, wait, wait!!!!
I didn't add the lasts part.

**Comment by romainguy** [comment]
Eh, too late :) You can send another PR.

**Comment by ThomasGorisse** [comment]
OK.
I also solved what I though was a raw/column inversion but was in fact a transpose forget.

**Comment by ThomasGorisse** [comment]
@romainguy 
Quick question:
Do you think that
```kotin
fun toEulerAngles(order: RotationsOrder = RotationsOrder.ZYX) = eulerAngles(this, order)
fun toQuaternion() = quaternion(this)
```
should be in fact
```kotin
fun toEulerAngles(order: RotationsOrder = RotationsOrder.ZYX) = eulerAngles(transpose(this), order)
fun toQuaternion() = quaternion(transpose(this))
```
Meaning those functions should extract the Euler angles ad Quaternion from a transposed Mat4 or from a rotation matrix:
```kotin
fun eulerAngles(m: Mat4, order: RotationsOrder = RotationsOrder.ZYX): Float3
fun quaternion(m: Mat4): Quaternion
```

**Comment by ThomasGorisse** [comment]
Because actually, to retrieve a Euler angles with a non ZYX order or a Quaternion from a transposed `Mat4` we have to call this:
```kotlin
quaternion(rotation(mat))
```

**Comment by romainguy** [comment]
Why would you need to transpose the matrix to convert to a quaternion?

**Comment by ThomasGorisse** [comment]
Yes, you are right this is a non sense.

It's more about an API probably miss understood between converting a rotation matrix to Quaternion and extracting the quaternion from a transposed matrix.
Cause we have the `val rotation: Float3` which does the extraction but no over `Mat4` getter for quaternion and Euler over then ZYX.

**Pull request merged**
