### PR TITLE
Fixed Mat2 `times` function

### PR DESCRIPTION
**Pull request by gilgoldzweig**
Fixed Mat2 `times` function, the multiplication of the matrix wasn't correct

### CODE REVIEW

**Comment by romainguy** [comment]
The current code is correct. Your change fails the unit test. You can validate the unit test with other matrix calculators like https://www.wolframalpha.com/input?i2d=true&i=%7B%7B1%2C2%7D%2C%7B3%2C4%7D%7D.%7B%7B2%2C0%7D%2C%7B1%2C2%7D%7D

**Comment by gilgoldzweig** [comment]
@romainguy You're right, my mistake was the order of how the elements are inserted into `Mat2` I expected the values to by inserted in an x,y x,y and you have it as x,x y,y 

  fun of(vararg a: Float): Mat2 {
            require(a.size >= 4)
            return Mat2(
                    Float2(a[0], a[2]),
                    Float2(a[1], a[3])
            )
        }

and my implementation was using 

  fun of(vararg a: Float): Mat2 {
            require(a.size >= 4)
            return Mat2(
                    Float2(a[0], a[1]),
                    Float2(a[2], a[3])
            )
        }

**Comment by romainguy** [comment]
The `of` function is designed to match the "math" notation (so row-major). The other constructors are column-major.

**Comment by gilgoldzweig** [comment]
Yeah, the mistake was on my side, I'm still new to the topic and your code didn't work for my use-case

**Pull request closed without merging**
